/**
 * @file Matrix_rep.h
 * @author Riley Horrix (horrixriley@gmail.com)
 * @brief Definition of internal matrix representation class
 * @version 0.1
 * @date 2024-07-22
 * 
 * Copyright (c) Riley Horrix 2024
 * 
 */

#pragma once 

#include <array>

namespace rmath {

  typedef unsigned int mat_dim;

  /**
   * @brief Class to represent the internal representation of matrix data.
   * 
   * @tparam rows Number of rows in the matrix.
   * @tparam cols Number of rows in the matrix.
   * @tparam D    Data type of the matrix.
   */
  template<mat_dim rows, mat_dim cols, class D> class MatrixRep {
    private:
      class MatrixRepProxy;
    public:
      /**
       * @brief Construct a new zero Matrix Rep object.
       * 
       */
      MatrixRep(void);

      /**
       * @brief Construct a new Matrix Rep object initialised to VALUE param.
       * 
       * @param value What value every entry the matrix is initialised to.
       */
      MatrixRep(const D value);

      /**
       * @brief Construct a new Matrixrep object from an initialiser list, Fills the matrix from the data row wise from row 1 to row ROWS.
       * 
       * @param data Values to fill the matrix with.
       */
      MatrixRep(const std::initializer_list<D>& data);

      /**
       * @brief Destroy the Matrix Rep object and allow polymorphism
       * 
       */
      virtual ~MatrixRep() {}

      /**
       * @brief Returns an intermediate object that can be array indexed to get the element
       *        at row ROW, column COLUMN. Indexed from 0.
       * 
       * @return MatrixRepProxy intermediate type.
       */
      D& operator() (mat_dim row, mat_dim column);

      MatrixRepProxy operator[] (mat_dim row) const {
        return MatrixRepProxy(this, &MatrixRep::get_elem, row);
      }

    protected:
      /**
       * @brief Internal method for getting an element from the raw data, override 
       *        this to change the layout of the rows and values. Indexes from 0
       * 
       * @param column 
       * @param row 
       * @return D elem at row ROW and column COLUMN.
       */
      virtual inline D& get_elem(mat_dim row, mat_dim column);

    private:
    /**
     * @brief The raw data
     * 
     */
      std::array<D, rows * cols> data;

    typedef D& (MatrixRep<rows, cols, D>::* get_elem_fn)(mat_dim, mat_dim) const; 

    /**
     * @brief Definition of MatrixRepProxy class, acts as an intermediate array indexing into MatrixRep
     * 
     * @tparam D 
     */
    class MatrixRepProxy {
    public:
      /**
       * @brief Construct a new Matrix Rep Proxy object
       * 
       */
      MatrixRepProxy(const MatrixRep* parent, get_elem_fn get_fn, mat_dim row): get_fn(get_fn), row(row), parent(parent) {}

      /**
       * @brief Construct a new Matrix Rep Proxy object from copy constructor
       * 
       * @param get_fn 
       * @param row 
       */
      MatrixRepProxy(const MatrixRepProxy& other): get_fn(other.get_fn), row(other.row), parent(other.parent) {}

      /**
       * @brief Destroy the Matrix Rep Proxy object
       * 
       */
      ~MatrixRepProxy() {}

      /**
       * @brief Complete this class's job by providing the other half of the 2D matrix array index for the column
       * 
       * @param column 
       * @return D& 
       */
      D& operator[] (mat_dim column) {
        return (parent->*get_fn)(row, column);
      }

    private:
      /**
       * @brief Reference to creator
       * 
       */
      get_elem_fn get_fn;

      /**
       * @brief The row this object indexes
       * 
       */
      const mat_dim row;

      /**
       * @brief Matrix this object was generated by
       * 
       */
      const MatrixRep* parent;
    };

  };

} // namespace rmath

/** Include Declarations */
#include "../../src/Matrix/MatrixRep.hpp"